### PR TITLE
Add beast tribe functions to data.yml

### PR DESCRIPTION
**Pull request by rvazarkar**

### CODE REVIEW

**Comment by daemitus** [comment]
Can you add these as entries to 
```  Client::Game::UI::PlayerState:
    funcs:
      0x140789110: SetCharacterName
      0x14078CA30: Initialize
      0x1407F2BF0: ctor
```

**Comment by daemitus** [comment]
@aers   Client::Game::UI::PlayerState: is the same as Client::Game::UI::UIModule::PlayerState right? If so, I assume we should fix the namespace.

**Comment by aers** [comment]
Anything with "UIModule::PlayerState" is probably an accident/mistake, it should be Client::Game::UI (even though this is a class with no vfuncs, it definitely doesn't belong to UIModule)

**Comment by daemitus** [comment]
Sorry, not uimodule, uistate. https://github.com/aers/FFXIVClientStructs/blob/main/FFXIVClientStructs/FFXIV/Client/Game/UI/UIState.cs

**Comment by aers** [comment]
Oh. I think its probably in Client::Game::UI and not inside UIModule, yeah.

**Pull request merged**
