### PR TITLE
Update AtkUnitBase and AddonContextMenu

### PR DESCRIPTION
**Pull request by daemitus**

### CODE REVIEW

**Comment by daemitus** [comment]
RE #195

**Comment by aers** [comment]
Double check Dalamud doesn't use this since it was from the context menu

**Comment by daemitus** [comment]
It does
https://github.com/goatcorp/Dalamud/blob/master/Dalamud/Game/Gui/ContextMenus/ContextMenu.cs#L215

**Comment by aers** [comment]
I dunno when goat plans to pull clientstructs again but a note will need to be made of this

**Pull request closed without merging**
