### PR TITLE
Add TargetSystem.AccessObject

### PR DESCRIPTION
**Pull request by marimelon**

### CODE REVIEW

**Comment by aers** [comment]
What does this function do? Bit too busy to check it myself right now

**Comment by pohky** [comment]
> What does this function do? Bit too busy to check it myself right now

from the looks of it start interacting/talk with the npc

**Comment by marimelon** [comment]
Start talk NPC, Open Retainer, Open MarketBortd,Open Aetheryte and Others.

It is called when you right-click on an object or when you
When you select a target and press decision on the gamepad, it is called.

**Comment by aers** [comment]
Ah okay thanks.

**Pull request merged**
