### PR TITLE
Update AgentBlacklist.cs

### PR DESCRIPTION
**Pull request by Aireil**
I couldn't find InfoProxy, not sure if it's a skill issue or if it's gone (probably the former) 🤡.

### CODE REVIEW

**Comment by Haselnussbomber** [comment]
https://github.com/aers/FFXIVClientStructs/blob/main/FFXIVClientStructs/FFXIV/Client/UI/Info/InfoProxyBlacklist.cs

**Comment by Aireil** [comment]
I meant the pointer in the agent

**Comment by Haselnussbomber** [comment]
Oops! 🤷‍♂️

**Comment by Aireil** [comment]
Turns out I'm not the only clown out here, I'll be sending you the invite to my circus 🎪

**Pull request merged**
