### PR TITLE
Fates and buddies

### PR DESCRIPTION
**Pull request by daemitus**

### CODE REVIEW

**Comment by daemitus** [comment]
Client::Game::Event::Fate is a guess, it's near other event stuff.

**Comment by daemitus** [comment]
If that is an event construct, should FateID be EventID? Maybe just ID.

**Comment by daemitus** [comment]
duh. it has rtti. fixing.

**Comment by daemitus** [comment]
done.

**Comment by daemitus** [comment]
well almost done. The question about FateID/EventID remains. FateContext has no parent.

**Comment by aers** [comment]
You moved the files but didn't change the namespace.

If FateId matches https://github.com/xivapi/ffxiv-datamining/blob/master/csv/Fate.csv it's definitely fate id

**Comment by daemitus** [comment]
Fixed the namespaces, made a guess as to the size of TrustManager size. Beat's me where the ctor/dtor is.

**Comment by daemitus** [comment]
SquadronOrTrust aka... "BattleBuddy"?

**Pull request merged**
