### PR TITLE
Fix a few offsets in UI3DModule

### PR DESCRIPTION
**Pull request by Pilzinsel64**
Fix offset of `NamePlateObjectInfoPointerArray` and `NamePlateObjectInfoCounter`
Thanks to Banana Bread for finding them!

### CODE REVIEW

**Comment by aers** [comment]
Those offsets changed because the object array was expanded again (to 599) in order to support 8 person cards.

So don't merge this until we can update the rest of the offsets too.

I'll try and do it tomorrow if no one else does.

**Comment by Pilzinsel64** [comment]
Ahhhh, that makes sense! Well, I'm not able to research that at all, so I'll leave that open for now. Just close it if not needed anymore.

**Comment by Pilzinsel64** [comment]
Might this be the same as for `RaptureAtkModule` and `RaptureAtkModule.NamePlateInfo`?
As this also seems to be broken somehow.

**Comment by aers** [comment]
Yes that offset nearly guaranteed to have shifted too. I'm going to bed right now so I'll fix it tomorrow if no one else has by then.

**Comment by Pilzinsel64** [comment]
Alright, thanks for the info! Have a good night and sleep well!

**Pull request merged**
